/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Entity.Boleto;
import Entity.Canciones;
import Entity.Encuesta;
import Entity.Sorteo;
import Entity.SuperClass;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srhad
 */
public class PantallaS extends javax.swing.JFrame {

    static Boleto boletoWin;
   
    ArrayList<Canciones> cancion;
    static ArrayList<Boleto> boleto;
    DefaultTableModel modelo;
    DefaultTableModel modelo2;

    /**
     * Creates new form PantallaS
     */
    public PantallaS() {
        
        this.setResizable(false);
        initComponents();
        cancion = Encuesta.getCanciones();
        actualizar();
    }
    
    public static void a(){
         boleto = SuperClass.listaboletos();
    }
    

    public void VotoTabla() {
        for (int i = 0; i < cancion.size(); i++) {
            String[] v = new String[3];
            v[0] = String.valueOf(cancion.get(i).getVoto());
            v[1] = cancion.get(i).getTitulo();
            v[2] = cancion.get(i).getArtista().getNombre();
            modelo2.addRow(v);
        }
    }

    public void Datotabla() {
        for (int i = 0; i < boleto.size(); i++) {
            String[] asdasd = new String[11];
            asdasd[0] = boleto.get(i).getOyente().getDocumento();
            asdasd[1] = boleto.get(i).getOyente().getNombre();
            asdasd[2] = boleto.get(i).getOyente().getGenero();
            asdasd[3] = String.valueOf(boleto.get(i).getOyente().getEdad());
            asdasd[4] = boleto.get(i).getOyente().getTelefono();
            asdasd[5] = boleto.get(i).getColor();
            asdasd[6] = String.valueOf(boleto.get(i).getNumero());
            asdasd[7] = boleto.get(i).getOyente().getCanciones().get(0).getArtista().getNombre();
            asdasd[8] = boleto.get(i).getOyente().getCanciones().get(0).getTitulo();
            asdasd[9] = boleto.get(i).getOyente().getCanciones().get(1).getTitulo();
            asdasd[10] = boleto.get(i).getOyente().getCanciones().get(2).getTitulo();
            modelo.addRow(asdasd);
        }
    }

    public void actualizar() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Documento");
        modelo.addColumn("Nombre");
        modelo.addColumn("Género");
        modelo.addColumn("Edad");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Color Boleto");
        modelo.addColumn("Número Boleto");
        modelo.addColumn("Nombre Artista");
        modelo.addColumn("Canción 1");
        modelo.addColumn("Canción 2");
        modelo.addColumn("Canción 3");
        this.Datotabla();
        this.tabal.setModel(modelo);

        modelo2 = new DefaultTableModel();
        modelo2.addColumn("Votos");
        modelo2.addColumn("Titulo Canción");
        modelo2.addColumn("Artista");
        this.VotoTabla();
        this.TabalVotos.setModel(modelo2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabal = new javax.swing.JTable();
        bttGanador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CBoleto = new javax.swing.JTextField();
        NBoleto = new javax.swing.JTextField();
        TextD = new javax.swing.JTextField();
        TextN = new javax.swing.JTextField();
        TextT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabalVotos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        calaca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Survey");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabal.setForeground(new java.awt.Color(255, 255, 255));
        tabal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre", "Genero", "Edad", "Telefono", "Color Boleto", "Numero Boleto", "Artista", "Cancion 1", "Cancion 2", "Cancion 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabal.setEnabled(false);
        tabal.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1180, 320));

        bttGanador.setForeground(new java.awt.Color(255, 255, 255));
        bttGanador.setText("Realizar Sorteo");
        bttGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGanadorActionPerformed(evt);
            }
        });
        jPanel1.add(bttGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 140, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ganador Sorteo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Color Boleto: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Número Boleto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Documento: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 650, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Teléfono:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, -1, -1));

        CBoleto.setEditable(false);
        CBoleto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CBoleto.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        CBoleto.setEnabled(false);
        jPanel1.add(CBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 250, -1));

        NBoleto.setEditable(false);
        NBoleto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        NBoleto.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        NBoleto.setEnabled(false);
        jPanel1.add(NBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 250, -1));

        TextD.setEditable(false);
        TextD.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TextD.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TextD.setEnabled(false);
        jPanel1.add(TextD, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, 250, -1));

        TextN.setEditable(false);
        TextN.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TextN.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TextN.setEnabled(false);
        jPanel1.add(TextN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 650, 250, -1));

        TextT.setEditable(false);
        TextT.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TextT.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        TextT.setEnabled(false);
        jPanel1.add(TextT, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 690, 250, -1));

        jLabel7.setFont(new java.awt.Font("SimSun", 3, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Music Survey");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Datos encuesta:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        TabalVotos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TabalVotos.setForeground(new java.awt.Color(255, 255, 255));
        TabalVotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Votos", "Titulo cancion", "Artista"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabalVotos.setEnabled(false);
        jScrollPane2.setViewportView(TabalVotos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 530, 320));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Votos canciones: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar encuesta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 140, 30));

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Actualizar Datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 140, 30));

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cerrar sesion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 30));

        calaca.setFont(new java.awt.Font("SimSun", 3, 48)); // NOI18N
        calaca.setForeground(new java.awt.Color(0, 0, 0));
        calaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.jpeg"))); // NOI18N
        calaca.setFocusCycleRoot(true);
        calaca.setName(""); // NOI18N
        jPanel1.add(calaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGanadorActionPerformed
        boletoWin=SuperClass.Ganador();
        this.CBoleto.setText(boletoWin.getColor());
        this.NBoleto.setText(String.valueOf( boletoWin.getNumero()));
        this.TextN.setText(boletoWin.getOyente().getNombre());
        this.TextD.setText(boletoWin.getOyente().getDocumento());
        this.TextT.setText(boletoWin.getOyente().getTelefono());

    }//GEN-LAST:event_bttGanadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         PantallaR pantallar = new PantallaR();

        pantallar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Realizar una función o acción cuando el JFrame se cierra
                actualizar();
                // Puedes realizar aquí la acción que necesites.
            }
        });
        pantallar.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actualizar();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PantallaInicio i=new PantallaInicio();
        i.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CBoleto;
    private javax.swing.JTextField NBoleto;
    private javax.swing.JTable TabalVotos;
    private javax.swing.JTextField TextD;
    private javax.swing.JTextField TextN;
    private javax.swing.JTextField TextT;
    private javax.swing.JButton bttGanador;
    private javax.swing.JLabel calaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabal;
    // End of variables declaration//GEN-END:variables
}
