/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CiudadC;
import Controller.ContinenteC;
import Controller.EstadoC;
import Controller.PaisC;
import Model.Entity.Ciudad;
import Model.Entity.Continente;
import Model.Entity.Estado;
import Model.Entity.Pais;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author juan
 */
public class Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar
     */
    public Eliminar() {
        this.setResizable(false);
        this.setLocationRelativeTo(null); 
        this.setLocation(this.getX() - 250, this.getY() - 220);
        initComponents();
        String valorSeleccionado = (String) ComboBoxTabla.getSelectedItem();
        System.out.println(valorSeleccionado);
    }

    private void EliminarCiudad() {
        CiudadC ciudad = new CiudadC();
        System.out.println(ComboBoxNombre.getSelectedItem());
        ciudad.EliminarRegistro((String) ComboBoxNombre.getSelectedItem());
    }

    private void EliminarContinente() {
        ContinenteC continente = new ContinenteC();
        System.out.println(ComboBoxNombre.getSelectedItem());
        continente.EliminarRegistro((String) ComboBoxNombre.getSelectedItem());

    }

    private void EliminarEstado() {
        EstadoC estado = new EstadoC();
        System.out.println(ComboBoxNombre.getSelectedItem());
        estado.EliminarRegistro((String) ComboBoxNombre.getSelectedItem());

    }

    private void EliminarPais() {
        PaisC pais = new PaisC();
        System.out.println(ComboBoxNombre.getSelectedItem());
        pais.EliminarRegistro((String) ComboBoxNombre.getSelectedItem());

    }

    private void ConsultaContinente() {

        try {
            ContinenteC controlador = new ContinenteC();
            ArrayList<Continente> listaDeProductos = controlador.ConsultarRegistro();

            for (Continente continente : listaDeProductos) {
                String descripcion = continente.getDescripcion();
                ComboBoxNombre.addItem(descripcion);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void ConsultaPais() {

        try {
            PaisC controlador = new PaisC();
            ArrayList<Pais> listaDeProductos = controlador.ConsultarRegistro();

            for (Pais pais : listaDeProductos) {
                String descripcion = pais.getDescripcion();
                ComboBoxNombre.addItem(descripcion);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void ConsultaEstado() {

        try {
            EstadoC controlador = new EstadoC();
            ArrayList<Estado> listaDeProductos = controlador.ConsultarRegistro();

            for (Estado estado : listaDeProductos) {
                String descripcion = estado.getDescripcion();
                ComboBoxNombre.addItem(descripcion);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void ConsultaCiudad() {

        try {
            CiudadC controlador = new CiudadC();
            ArrayList<Ciudad> listaDeProductos = controlador.ConsultarRegistro();

            for (Ciudad ciudad : listaDeProductos) {
                String descripcion = ciudad.getDescripcion();
                ComboBoxNombre.addItem(descripcion);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboBoxTabla = new javax.swing.JComboBox<>();
        ButtonEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ComboBoxNombre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Qué desea Eliminar?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        ComboBoxTabla.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Continente", "Pais", "Estado", "Ciudad" }));
        ComboBoxTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTablaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 115, -1));

        ButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        ComboBoxNombre.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        ComboBoxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNombreActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Eliminar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/f219c8f84503eee32016a115be66a4f4.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTablaActionPerformed
        String valorSeleccionado = (String) ComboBoxTabla.getSelectedItem();
        System.out.println(valorSeleccionado);
        ComboBoxNombre.removeAllItems();

        switch (valorSeleccionado) {
            case "Pais":
                this.ConsultaPais();
                break;
            case "Estado":
                this.ConsultaEstado();
                break;
            case "Ciudad":
                this.ConsultaCiudad();
                break;
            case "Continente":
                this.ConsultaContinente();
                break;
            default:
                // No se hace nada
                break;
        }

    }//GEN-LAST:event_ComboBoxTablaActionPerformed

    private void ComboBoxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxNombreActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        String valorSeleccionado = (String) ComboBoxTabla.getSelectedItem();
        System.out.println(valorSeleccionado);
        switch (valorSeleccionado) {
            case "Pais":
                this.EliminarPais();
                break;
            case "Estado":
                this.EliminarEstado();
                break;
            case "Ciudad":
                this.EliminarCiudad();
                break;
            case "Continente":
                this.EliminarContinente();
                break;
            default:
                // No se hace nada
                break;
        }
    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LugaresV jframe = new LugaresV();
        jframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JComboBox<String> ComboBoxNombre;
    private javax.swing.JComboBox<String> ComboBoxTabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
