/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CiudadC;
import Controller.ContinenteC;
import Controller.EstadoC;
import Controller.PaisC;
import Model.Entity.Ciudad;
import Model.Entity.Continente;
import Model.Entity.Estado;
import Model.Entity.Pais;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;

/**
 *
 * @author juan
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jTextField1.setPreferredSize(new Dimension(200, 30));
        jTextField2.setPreferredSize(new Dimension(200, 30));
        ComboBoxSeconKey.setVisible(false);
        this.SelectComboBox();
        ComboBoxUbicacion.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    SelectComboBox();
                }
            }
        });
        this.selectId();
        ComboBoxId.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    selectId();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxUbicacion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Ubicacion = new javax.swing.JLabel();
        ComboBoxSeconKey = new javax.swing.JComboBox<>();
        ComboBoxId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComboBoxUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Continente", "Pais", "Estado", "Ciudad" }));
        ComboBoxUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxUbicacionActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 114, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Qué desea Modificar?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo postal:");

        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripcion:");

        jTextField2.setForeground(new java.awt.Color(255, 255, 255));

        ComboBoxSeconKey.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxSeconKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxSeconKeyActionPerformed(evt);
            }
        });

        ComboBoxId.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxIdActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxSeconKey, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ComboBoxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboBoxSeconKey)
                    .addComponent(Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 105, -1, -1));

        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modificar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 14, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/f219c8f84503eee32016a115be66a4f4.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxUbicacionActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        String valorSeleccionado = (String) ComboBoxUbicacion.getSelectedItem();
        String valSeleccionado = (String) ComboBoxSeconKey.getSelectedItem();
        String Seleccionado = (String) ComboBoxId.getSelectedItem();

        try {

            String Continente;

            String pais;
            String Estado;
            String Ciudad;

            // Captura de datos de entrada
            if ("Pais".equals(valorSeleccionado)) {
                String descripcion1;
                String codigoPostal1;

                codigoPostal1 = jTextField1.getText();
                descripcion1 = jTextField2.getText();
                PaisC agregarpais = new PaisC();
                agregarpais.ModificarRegistro(Seleccionado, codigoPostal1, descripcion1, valSeleccionado);
            } else if ("Estado".equals(valorSeleccionado)) {
                String descripcion;
                String codigoPostal;

                codigoPostal = jTextField1.getText();
                descripcion = jTextField2.getText();
                EstadoC agregarEstado = new EstadoC();
                agregarEstado.ModificarRegistro(Seleccionado, codigoPostal, descripcion, valSeleccionado);
            } else if ("Ciudad".equals(valorSeleccionado)) {
                String descripcion;
                String codigoPostal;

                codigoPostal = jTextField1.getText();
                descripcion = jTextField2.getText();
                CiudadC agregarCiudad = new CiudadC();
                agregarCiudad.ModificarRegistro(Seleccionado, codigoPostal, descripcion, valSeleccionado);
            } else if ("Continente".equals(valorSeleccionado)) {
                String descripcion;
                String codigoPostal;

                codigoPostal = jTextField1.getText();
                descripcion = jTextField2.getText();
                ContinenteC agregarpais = new ContinenteC();
                agregarpais.ModificarRegistro(Seleccionado, codigoPostal, descripcion);
            } else {
            };

        } catch (Exception e) {
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ComboBoxIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LugaresV jframe = new LugaresV();
        jframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboBoxSeconKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxSeconKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxSeconKeyActionPerformed

    private String selectId() {
        String selectedItemId = (String) ComboBoxId.getSelectedItem();
        return selectedItemId;
    }

    private void ComboBoxIdContinente() {
        Ubicacion.setText("");
        ComboBoxSeconKey.setVisible(false);
        ContinenteC controlador = new ContinenteC();
        ArrayList<Continente> listaDeProductos = controlador.ConsultarRegistro();

        ComboBoxId.removeAllItems();

        for (int i = 0; i < listaDeProductos.size(); i++) {
            ComboBoxId.addItem(String.valueOf(listaDeProductos.get(i).getDescripcion()));
        }
    }

    private void ComboBoxIdPais() {
        Ubicacion.setText("Continente Id:");
        ComboBoxSeconKey.setVisible(true);
        PaisC controlador = new PaisC();
        ArrayList<Pais> listaDeProductos = controlador.ConsultarRegistro();

        ComboBoxId.removeAllItems();

        for (int i = 0; i < listaDeProductos.size(); i++) {
            ComboBoxId.addItem(String.valueOf(listaDeProductos.get(i).getDescripcion()));
        }

        ContinenteC control = new ContinenteC();
        ArrayList<Continente> continentes = control.ConsultarRegistro();

        ComboBoxSeconKey.removeAllItems();

        for (int i = 0; i < continentes.size(); i++) {
            ComboBoxSeconKey.addItem(String.valueOf(continentes.get(i).getDescripcion()));
        }
    }

    private void ComboBoxIdeEstado() {
        Ubicacion.setText("Pais Id:");
        ComboBoxSeconKey.setVisible(true);
        EstadoC controlador = new EstadoC();
        ArrayList<Estado> listaDeProductos = controlador.ConsultarRegistro();

        ComboBoxId.removeAllItems();

        for (int i = 0; i < listaDeProductos.size(); i++) {
            ComboBoxId.addItem(String.valueOf(listaDeProductos.get(i).getDescripcion()));
        }

        PaisC control = new PaisC();
        ArrayList<Pais> paises = control.ConsultarRegistro();

        ComboBoxSeconKey.removeAllItems();

        for (int i = 0; i < paises.size(); i++) {
            ComboBoxSeconKey.addItem(String.valueOf(paises.get(i).getDescripcion()));
        }
    }

    private void ComboBoxIdCiudad() {
        Ubicacion.setText("Estado Id:");
        ComboBoxSeconKey.setVisible(true);
        CiudadC controlador = new CiudadC();
        ArrayList<Ciudad> listaDeProductos = controlador.ConsultarRegistro();

        ComboBoxId.removeAllItems();

        for (int i = 0; i < listaDeProductos.size(); i++) {
            ComboBoxId.addItem(String.valueOf(listaDeProductos.get(i).getDescripcion()));
        }

        EstadoC control = new EstadoC();
        ArrayList<Estado> estados = control.ConsultarRegistro();

        ComboBoxSeconKey.removeAllItems();

        for (int i = 0; i < estados.size(); i++) {
            ComboBoxSeconKey.addItem(String.valueOf(estados.get(i).getDescripcion()));
        }
    }

    private void SelectComboBox() {
        String valorSeleccionado = (String) ComboBoxUbicacion.getSelectedItem();
        System.out.println("View.Registrar.jToggleButton1ActionPerformed()" + valorSeleccionado);

        try {

            // Captura de datos de entrada
            switch (valorSeleccionado) {
                case "Pais":
                    ComboBoxIdPais();
                    break;
                case "Estado":
                    ComboBoxIdeEstado();
                    break;
                case "Ciudad":
                    ComboBoxIdCiudad();
                    break;
                case "Continente":
                    ComboBoxIdContinente();
                    break;
                default:
                    // No se hace nada
                    break;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxId;
    private javax.swing.JComboBox<String> ComboBoxSeconKey;
    private javax.swing.JComboBox<String> ComboBoxUbicacion;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Ubicacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
